#!/bin/bash
ln -s /usr/bin/gcc-6 /usr/bin/gcc
ln -s /usr/bin/gcc-ar-6 /usr/bin/gcc-ar
ln -s /usr/bin/gcc-nm-6 /usr/bin/gcc-nm
ln -s /usr/bin/gcc-ranlib-6 /usr/bin/gcc-ranlib
ln -s /usr/bin/g++-6 /usr/bin/g++
